// src/main/webapp/app/entities/bounty/bounty-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './bounty.reducer';
import { IBounty } from 'app/shared/model/bounty.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IBountyDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const BountyDetail = (props: IBountyDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { bountyEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          Bounty [<b>{bountyEntity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="status">Status</span>
          </dt>
          <dd>{bountyEntity.status}</dd>
          <dt>
            <span id="url">Url</span>
          </dt>
          <dd>{bountyEntity.url}</dd>
          <dt>
            <span id="amount">Amount</span>
          </dt>
          <dd>{bountyEntity.amount}</dd>
          <dt>
            <span id="experience">Experience</span>
          </dt>
          <dd>{bountyEntity.experience}</dd>
          <dt>
            <span id="commitment">Commitment</span>
          </dt>
          <dd>{bountyEntity.commitment}</dd>
          <dt>
            <span id="type">Type</span>
          </dt>
          <dd>{bountyEntity.type}</dd>
          <dt>
            <span id="category">Category</span>
          </dt>
          <dd>{bountyEntity.category}</dd>
          <dt>
            <span id="keywords">Keywords</span>
          </dt>
          <dd>{bountyEntity.keywords}</dd>
          <dt>
            <span id="permission">Permission</span>
          </dt>
          <dd>{bountyEntity.permission ? 'true' : 'false'}</dd>
          <dt>
            <span id="expires">Expires</span>
          </dt>
          <dd>{bountyEntity.expires ? <TextFormat value={bountyEntity.expires} type="date" format={APP_LOCAL_DATE_FORMAT} /> : null}</dd>
          <dt>Issue</dt>
          <dd>{bountyEntity.issue ? bountyEntity.issue.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/bounty" replace color="info">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/bounty/${bountyEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ bounty }: IRootState) => ({
  bountyEntity: bounty.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(BountyDetail);

// src/main/webapp/app/entities/bounty/bounty-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IBounty } from 'app/shared/model/bounty.model';

@Component({
  selector: 'jhi-bounty-detail',
  templateUrl: './bounty-detail.component.html',
})
export class BountyDetailComponent implements OnInit {
  bounty: IBounty | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ bounty }) => (this.bounty = bounty));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="bounty">
            <h2><span jhiTranslate="bountiesApp.bounty.detail.title">Bounty</span> {{ bounty.id }}</h2>

            <hr>

            <jhi-alert-error></jhi-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="bountiesApp.bounty.status">Status</span></dt>
                <dd>
                    <span jhiTranslate="{{ 'bountiesApp.Status.' + bounty.status }}">{{ bounty.status }}</span>
                </dd>
                <dt><span jhiTranslate="bountiesApp.bounty.url">Url</span></dt>
                <dd>
                    <span>{{ bounty.url }}</span>
                </dd>
                <dt><span jhiTranslate="bountiesApp.bounty.amount">Amount</span></dt>
                <dd>
                    <span>{{ bounty.amount }}</span>
                </dd>
                <dt><span jhiTranslate="bountiesApp.bounty.experience">Experience</span></dt>
                <dd>
                    <span jhiTranslate="{{ 'bountiesApp.Experience.' + bounty.experience }}">{{ bounty.experience }}</span>
                </dd>
                <dt><span jhiTranslate="bountiesApp.bounty.commitment">Commitment</span></dt>
                <dd>
                    <span>{{ bounty.commitment }}</span>
                </dd>
                <dt><span jhiTranslate="bountiesApp.bounty.type">Type</span></dt>
                <dd>
                    <span jhiTranslate="{{ 'bountiesApp.Type.' + bounty.type }}">{{ bounty.type }}</span>
                </dd>
                <dt><span jhiTranslate="bountiesApp.bounty.category">Category</span></dt>
                <dd>
                    <span jhiTranslate="{{ 'bountiesApp.Category.' + bounty.category }}">{{ bounty.category }}</span>
                </dd>
                <dt><span jhiTranslate="bountiesApp.bounty.keywords">Keywords</span></dt>
                <dd>
                    <span>{{ bounty.keywords }}</span>
                </dd>
                <dt><span jhiTranslate="bountiesApp.bounty.permission">Permission</span></dt>
                <dd>
                    <span>{{ bounty.permission }}</span>
                </dd>
                <dt><span jhiTranslate="bountiesApp.bounty.expires">Expires</span></dt>
                <dd>
                    <span>{{ bounty.expires }}</span>
                </dd>
                <dt><span jhiTranslate="bountiesApp.bounty.issue">Issue</span></dt>
                <dd>
                    <div *ngIf="bounty.issue">
                        <a [routerLink]="['/issue', bounty.issue?.id, 'view']">{{ bounty.issue?.id }}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/bounties', bounty.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
            </button>
        </div>
    </div>
</div>
