// src/main/webapp/app/entities/bounty/bounty.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IBounty } from 'app/shared/model/bounty.model';
import { BountyService } from './bounty.service';
import { BountyDeleteDialogComponent } from './bounty-delete-dialog.component';

@Component({
  selector: 'jhi-bounty',
  templateUrl: './bounty.component.html',
})
export class BountyComponent implements OnInit, OnDestroy {
  bounty?: IBounty[];
  eventSubscriber?: Subscription;
  currentSearch: string;

  constructor(
    protected bountyService: BountyService,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal,
    protected activatedRoute: ActivatedRoute
  ) {
    this.currentSearch =
      this.activatedRoute.snapshot && this.activatedRoute.snapshot.queryParams['search']
        ? this.activatedRoute.snapshot.queryParams['search']
        : '';
  }

  loadAll(): void {
    if (this.currentSearch) {
      this.bountyService
        .search({
          query: this.currentSearch,
        })
        .subscribe((res: HttpResponse<IBounty[]>) => (this.bounty = res.body || []));
      return;
    }

    this.bountyService.query().subscribe((res: HttpResponse<IBounty[]>) => (this.bounty = res.body || []));
  }

  search(query: string): void {
    this.currentSearch = query;
    this.loadAll();
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInBounty();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IBounty): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInBounty(): void {
    this.eventSubscriber = this.eventManager.subscribe('bountyListModification', () => this.loadAll());
  }

  delete(bounty: IBounty): void {
    const modalRef = this.modalService.open(BountyDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.bounty = bounty;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="bountiesApp.bounty.home.title">Bounty</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-bounty" [routerLink]="['/bounties/new']">
            <fa-icon icon="plus"></fa-icon>
            <span class="hidden-sm-down"  jhiTranslate="bountiesApp.bounty.home.createLabel">
            Create a new Bounty
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="row">
        <div class="col-sm-12">
            <form name="searchForm" class="form-inline">
                <div class="input-group w-100 mt-3">
                    <input type="text" class="form-control" [(ngModel)]="currentSearch" id="currentSearch" name="currentSearch" placeholder="{{ 'bountiesApp.bounty.home.search' | translate }}">

                    <button class="input-group-append btn btn-info" (click)="search(currentSearch)">
                        <fa-icon icon="search"></fa-icon>
                    </button>

                    <button class="input-group-append btn btn-danger" (click)="search('')" *ngIf="currentSearch">
                        <fa-icon icon="trash-alt"></fa-icon>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="alert alert-warning" id="no-result" *ngIf="bounty?.length === 0">
        <span jhiTranslate="bountiesApp.bounty.home.notFound">No Bounty found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="bounty && bounty.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span jhiTranslate="global.field.id">ID</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounty.status">Status</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounty.url">Url</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounty.amount">Amount</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounty.experience">Experience</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounty.commitment">Commitment</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounty.type">Type</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounty.category">Category</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounty.keywords">Keywords</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounty.permission">Permission</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounty.expires">Expires</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounty.issue">Issue</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let bounty of bounty ;trackBy: trackId">
                    <td><a [routerLink]="['/bounties', bounty.id, 'view']">{{ bounty.id }}</a></td>
                    <td jhiTranslate="{{ 'bountiesApp.Status.' + bounty.status }}">{{ bounty.status }}</td>
                    <td>{{ bounty.url }}</td>
                    <td>{{ bounty.amount }}</td>
                    <td jhiTranslate="{{ 'bountiesApp.Experience.' + bounty.experience }}">{{ bounty.experience }}</td>
                    <td>{{ bounty.commitment }}</td>
                    <td jhiTranslate="{{ 'bountiesApp.Type.' + bounty.type }}">{{ bounty.type }}</td>
                    <td jhiTranslate="{{ 'bountiesApp.Category.' + bounty.category }}">{{ bounty.category }}</td>
                    <td>{{ bounty.keywords }}</td>
                    <td>{{ bounty.permission }}</td>
                    <td>{{ bounty.expires | date:'mediumDate' }}</td>
                    <td>
                        <div *ngIf="bounties.issue">
                            <a [routerLink]="['/issue', bounties.issue?.id, 'view']" >{{ bounties.issue?.id }}</a>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/bounties', bounty.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/bounties', bounty.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(bounty)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/bounty/bounty.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from './bounty.reducer';
import { IBounty } from 'app/shared/model/bounty.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IBountyProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Bounty = (props: IBountyProps) => {
  const [search, setSearch] = useState('');

  useEffect(() => {
    props.getEntities();
  }, []);

  const startSearching = () => {
    if (search) {
      props.getSearchEntities(search);
    }
  };

  const clear = () => {
    setSearch('');
    props.getEntities();
  };

  const handleSearch = event => setSearch(event.target.value);

  const { bountyList, match, loading } = props;
  return (
    <div>
      <h2 id="bounty-heading">
        <Translate contentKey="bountiesApp.bounty.home.title">Bounties</Translate>
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp;
          <Translate contentKey="bountiesApp.bounty.home.createLabel">Create new Bounty</Translate>
        </Link>
      </h2>
      <Row>
        <Col sm="12">
          <AvForm onSubmit={startSearching}>
            <AvGroup>
              <InputGroup>
                <AvInput
                  type="text"
                  name="search"
                  value={search}
                  onChange={handleSearch}
                  placeholder={translate('bountiesApp.bounty.home.search')}
                />
                <Button className="input-group-addon">
                  <FontAwesomeIcon icon="search" />
                </Button>
                <Button type="reset" className="input-group-addon" onClick={clear}>
                  <FontAwesomeIcon icon="trash" />
                </Button>
              </InputGroup>
            </AvGroup>
          </AvForm>
        </Col>
      </Row>
      <div className="table-responsive">
        {bountyList && bountyList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="bountiesApp.bounty.status">Status</Translate>
                </th>
                <th>
                  <Translate contentKey="bountiesApp.bounty.url">Url</Translate>
                </th>
                <th>
                  <Translate contentKey="bountiesApp.bounty.amount">Amount</Translate>
                </th>
                <th>
                  <Translate contentKey="bountiesApp.bounty.experience">Experience</Translate>
                </th>
                <th>
                  <Translate contentKey="bountiesApp.bounty.commitment">Commitment</Translate>
                </th>
                <th>
                  <Translate contentKey="bountiesApp.bounty.type">Type</Translate>
                </th>
                <th>
                  <Translate contentKey="bountiesApp.bounty.category">Category</Translate>
                </th>
                <th>
                  <Translate contentKey="bountiesApp.bounty.keywords">Keywords</Translate>
                </th>
                <th>
                  <Translate contentKey="bountiesApp.bounty.permission">Permission</Translate>
                </th>
                <th>
                  <Translate contentKey="bountiesApp.bounty.expires">Expires</Translate>
                </th>
                <th>
                  <Translate contentKey="bountiesApp.bounty.issue">Issue</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {bountyList.map((bounty, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${bounty.id}`} color="link" size="sm">
                      {bounty.id}
                    </Button>
                  </td>
                  <td>
                    <Translate contentKey={`bountiesApp.Status.${bounty.status}`} />
                  </td>
                  <td>{bounty.url}</td>
                  <td>{bounty.amount}</td>
                  <td>
                    <Translate contentKey={`bountiesApp.Experience.${bounty.experience}`} />
                  </td>
                  <td>{bounty.commitment}</td>
                  <td>
                    <Translate contentKey={`bountiesApp.Type.${bounty.type}`} />
                  </td>
                  <td>
                    <Translate contentKey={`bountiesApp.Category.${bounty.category}`} />
                  </td>
                  <td>{bounty.keywords}</td>
                  <td>{bounty.permission ? 'true' : 'false'}</td>
                  <td>{bounty.expires ? <TextFormat type="date" value={bounty.expires} format={APP_LOCAL_DATE_FORMAT} /> : null}</td>
                  <td>{bounty.issue ? <Link to={`issue/${bounty.issue.id}`}>{bounty.issue.id}</Link> : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${bounty.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${bounty.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${bounty.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="bountiesApp.bounty.home.notFound">No Bounties found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

const mapStateToProps = ({ bounty }: IRootState) => ({
  bountyList: bounty.entities,
  loading: bounty.loading,
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Bounty);
