// src/main/webapp/app/entities/funding/funding-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './funding.reducer';
import { IFunding } from 'app/shared/model/funding.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IFundingDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const FundingDetail = (props: IFundingDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { fundingEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          <Translate contentKey="bountiesApp.funding.detail.title">Funding</Translate> [<b>{fundingEntity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="amount">
              <Translate contentKey="bountiesApp.funding.amount">Amount</Translate>
            </span>
          </dt>
          <dd>{fundingEntity.amount}</dd>
          <dt>
            <span id="mode">
              <Translate contentKey="bountiesApp.funding.mode">Mode</Translate>
            </span>
          </dt>
          <dd>{fundingEntity.mode}</dd>
          <dt>
            <span id="paymentAuth">
              <Translate contentKey="bountiesApp.funding.paymentAuth">Payment Auth</Translate>
            </span>
          </dt>
          <dd>{fundingEntity.paymentAuth ? 'true' : 'false'}</dd>
          <dt>
            <Translate contentKey="bountiesApp.funding.bounty">Bounty</Translate>
          </dt>
          <dd>{fundingEntity.bounty ? fundingEntity.bounty.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/funding" replace color="info">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/funding/${fundingEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ funding }: IRootState) => ({
  fundingEntity: funding.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(FundingDetail);

// src/main/webapp/app/entities/funding/funding-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IFunding } from 'app/shared/model/funding.model';

@Component({
  selector: 'jhi-funding-detail',
  templateUrl: './funding-detail.component.html',
})
export class FundingDetailComponent implements OnInit {
  funding: IFunding | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ funding }) => (this.funding = funding));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="funding">
            <h2><span jhiTranslate="bountiesApp.funding.detail.title">Funding</span> {{ funding.id }}</h2>

            <hr>

            <jhi-alert-error></jhi-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="bountiesApp.funding.amount">Amount</span></dt>
                <dd>
                    <span>{{ funding.amount }}</span>
                </dd>
                <dt><span jhiTranslate="bountiesApp.funding.mode">Mode</span></dt>
                <dd>
                    <span>{{ funding.mode }}</span>
                </dd>
                <dt><span jhiTranslate="bountiesApp.funding.paymentAuth">Payment Auth</span></dt>
                <dd>
                    <span>{{ funding.paymentAuth }}</span>
                </dd>
                <dt><span jhiTranslate="bountiesApp.funding.bounties">Bounties</span></dt>
                <dd>
                    <div *ngIf="funding.bounties">
                        <a [routerLink]="['/bounties', funding.bounties?.id, 'view']">{{ funding.bounties?.id }}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/funding', funding.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
            </button>
        </div>
    </div>
</div>
