// src/main/webapp/app/entities/funding/funding.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IFunding } from 'app/shared/model/funding.model';
import { FundingService } from './funding.service';
import { FundingDeleteDialogComponent } from './funding-delete-dialog.component';

@Component({
  selector: 'jhi-funding',
  templateUrl: './funding.component.html',
})
export class FundingComponent implements OnInit, OnDestroy {
  fundings?: IFunding[];
  eventSubscriber?: Subscription;
  currentSearch: string;

  constructor(
    protected fundingService: FundingService,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal,
    protected activatedRoute: ActivatedRoute
  ) {
    this.currentSearch =
      this.activatedRoute.snapshot && this.activatedRoute.snapshot.queryParams['search']
        ? this.activatedRoute.snapshot.queryParams['search']
        : '';
  }

  loadAll(): void {
    if (this.currentSearch) {
      this.fundingService
        .search({
          query: this.currentSearch,
        })
        .subscribe((res: HttpResponse<IFunding[]>) => (this.fundings = res.body || []));
      return;
    }

    this.fundingService.query().subscribe((res: HttpResponse<IFunding[]>) => (this.fundings = res.body || []));
  }

  search(query: string): void {
    this.currentSearch = query;
    this.loadAll();
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInFundings();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IFunding): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInFundings(): void {
    this.eventSubscriber = this.eventManager.subscribe('fundingListModification', () => this.loadAll());
  }

  delete(funding: IFunding): void {
    const modalRef = this.modalService.open(FundingDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.funding = funding;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="bountiesApp.funding.home.title">Fundings</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-funding" [routerLink]="['/funding/new']">
            <fa-icon icon="plus"></fa-icon>
            <span class="hidden-sm-down"  jhiTranslate="bountiesApp.funding.home.createLabel">
            Create a new Funding
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="row">
        <div class="col-sm-12">
            <form name="searchForm" class="form-inline">
                <div class="input-group w-100 mt-3">
                    <input type="text" class="form-control" [(ngModel)]="currentSearch" id="currentSearch" name="currentSearch" placeholder="{{ 'bountiesApp.funding.home.search' | translate }}">

                    <button class="input-group-append btn btn-info" (click)="search(currentSearch)">
                        <fa-icon icon="search"></fa-icon>
                    </button>

                    <button class="input-group-append btn btn-danger" (click)="search('')" *ngIf="currentSearch">
                        <fa-icon icon="trash-alt"></fa-icon>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="alert alert-warning" id="no-result" *ngIf="fundings?.length === 0">
        <span jhiTranslate="bountiesApp.funding.home.notFound">No fundings found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="fundings && fundings.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span jhiTranslate="global.field.id">ID</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.funding.amount">Amount</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.funding.mode">Mode</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.funding.paymentAuth">Payment Auth</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.funding.bounties">Bounties</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let funding of fundings ;trackBy: trackId">
                    <td><a [routerLink]="['/funding', funding.id, 'view']">{{ funding.id }}</a></td>
                    <td>{{ funding.amount }}</td>
                    <td>{{ funding.mode }}</td>
                    <td>{{ funding.paymentAuth }}</td>
                    <td>
                        <div *ngIf="funding.bounties">
                            <a [routerLink]="['/bounties', funding.bounties?.id, 'view']" >{{ funding.bounties?.id }}</a>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/funding', funding.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/funding', funding.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(funding)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/funding/funding.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from './funding.reducer';
import { IFunding } from 'app/shared/model/funding.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IFundingProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Funding = (props: IFundingProps) => {
  const [search, setSearch] = useState('');

  useEffect(() => {
    props.getEntities();
  }, []);

  const startSearching = () => {
    if (search) {
      props.getSearchEntities(search);
    }
  };

  const clear = () => {
    setSearch('');
    props.getEntities();
  };

  const handleSearch = event => setSearch(event.target.value);

  const { fundingList, match, loading } = props;
  return (
    <div>
      <h2 id="funding-heading">
        <Translate contentKey="bountiesApp.funding.home.title">Fundings</Translate>
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp;
          <Translate contentKey="bountiesApp.funding.home.createLabel">Create new Funding</Translate>
        </Link>
      </h2>
      <Row>
        <Col sm="12">
          <AvForm onSubmit={startSearching}>
            <AvGroup>
              <InputGroup>
                <AvInput
                  type="text"
                  name="search"
                  value={search}
                  onChange={handleSearch}
                  placeholder={translate('bountiesApp.funding.home.search')}
                />
                <Button className="input-group-addon">
                  <FontAwesomeIcon icon="search" />
                </Button>
                <Button type="reset" className="input-group-addon" onClick={clear}>
                  <FontAwesomeIcon icon="trash" />
                </Button>
              </InputGroup>
            </AvGroup>
          </AvForm>
        </Col>
      </Row>
      <div className="table-responsive">
        {fundingList && fundingList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="bountiesApp.funding.amount">Amount</Translate>
                </th>
                <th>
                  <Translate contentKey="bountiesApp.funding.mode">Mode</Translate>
                </th>
                <th>
                  <Translate contentKey="bountiesApp.funding.paymentAuth">Payment Auth</Translate>
                </th>
                <th>
                  <Translate contentKey="bountiesApp.funding.bounty">Bounty</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {fundingList.map((funding, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${funding.id}`} color="link" size="sm">
                      {funding.id}
                    </Button>
                  </td>
                  <td>{funding.amount}</td>
                  <td>{funding.mode}</td>
                  <td>{funding.paymentAuth ? 'true' : 'false'}</td>
                  <td>{funding.bounty ? <Link to={`bounty/${funding.bounty.id}`}>{funding.bounty.id}</Link> : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${funding.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${funding.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${funding.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="bountiesApp.funding.home.notFound">No Fundings found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

const mapStateToProps = ({ funding }: IRootState) => ({
  fundingList: funding.entities,
  loading: funding.loading,
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Funding);
