// src/main/webapp/app/entities/bounties/bounties.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { ICrudSearchAction, ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from './bounties.reducer';
import { IBounties } from 'app/shared/model/bounties.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IBountiesProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Bounties = (props: IBountiesProps) => {
  const [search, setSearch] = useState('');

  useEffect(() => {
    props.getEntities();
  }, []);

  const startSearching = () => {
    if (search) {
      props.getSearchEntities(search);
    }
  };

  const clear = () => {
    setSearch('');
    props.getEntities();
  };

  const handleSearch = event => setSearch(event.target.value);

  const { bountiesList, match, loading } = props;
  return (
    <div>
      <h2 id="bounties-heading">
        Bounties
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp; Create new Bounties
        </Link>
      </h2>
      <Row>
        <Col sm="12">
          <AvForm onSubmit={startSearching}>
            <AvGroup>
              <InputGroup>
                <AvInput type="text" name="search" value={search} onChange={handleSearch} placeholder="Search" />
                <Button className="input-group-addon">
                  <FontAwesomeIcon icon="search" />
                </Button>
                <Button type="reset" className="input-group-addon" onClick={clear}>
                  <FontAwesomeIcon icon="trash" />
                </Button>
              </InputGroup>
            </AvGroup>
          </AvForm>
        </Col>
      </Row>
      <div className="table-responsive">
        {bountiesList && bountiesList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>ID</th>
                <th>Status</th>
                <th>Url</th>
                <th>Amount</th>
                <th>Experience</th>
                <th>Commitment</th>
                <th>Type</th>
                <th>Category</th>
                <th>Keywords</th>
                <th>Permission</th>
                <th>Expires</th>
                <th>Issue</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {bountiesList.map((bounties, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${bounties.id}`} color="link" size="sm">
                      {bounties.id}
                    </Button>
                  </td>
                  <td>{bounties.status}</td>
                  <td>{bounties.url}</td>
                  <td>{bounties.amount}</td>
                  <td>{bounties.experience}</td>
                  <td>{bounties.commitment}</td>
                  <td>{bounties.type}</td>
                  <td>{bounties.category}</td>
                  <td>{bounties.keywords}</td>
                  <td>{bounties.permission ? 'true' : 'false'}</td>
                  <td>{bounties.expires ? <TextFormat type="date" value={bounties.expires} format={APP_LOCAL_DATE_FORMAT} /> : null}</td>
                  <td>{bounties.issue ? <Link to={`issue/${bounties.issue.id}`}>{bounties.issue.id}</Link> : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${bounties.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${bounties.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${bounties.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Bounties found</div>
        )}
      </div>
    </div>
  );
};

const mapStateToProps = ({ bounties }: IRootState) => ({
  bountiesList: bounties.entities,
  loading: bounties.loading,
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Bounties);

// src/main/webapp/app/entities/bounties/bounties.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IBounties } from 'app/shared/model/bounties.model';
import { BountiesService } from './bounties.service';
import { BountiesDeleteDialogComponent } from './bounties-delete-dialog.component';

@Component({
  selector: 'jhi-bounties',
  templateUrl: './bounties.component.html',
})
export class BountiesComponent implements OnInit, OnDestroy {
  bounties?: IBounties[];
  eventSubscriber?: Subscription;
  currentSearch: string;

  constructor(
    protected bountiesService: BountiesService,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal,
    protected activatedRoute: ActivatedRoute
  ) {
    this.currentSearch =
      this.activatedRoute.snapshot && this.activatedRoute.snapshot.queryParams['search']
        ? this.activatedRoute.snapshot.queryParams['search']
        : '';
  }

  loadAll(): void {
    if (this.currentSearch) {
      this.bountiesService
        .search({
          query: this.currentSearch,
        })
        .subscribe((res: HttpResponse<IBounties[]>) => (this.bounties = res.body || []));
      return;
    }

    this.bountiesService.query().subscribe((res: HttpResponse<IBounties[]>) => (this.bounties = res.body || []));
  }

  search(query: string): void {
    this.currentSearch = query;
    this.loadAll();
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInBounties();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IBounties): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInBounties(): void {
    this.eventSubscriber = this.eventManager.subscribe('bountiesListModification', () => this.loadAll());
  }

  delete(bounties: IBounties): void {
    const modalRef = this.modalService.open(BountiesDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.bounties = bounties;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="bountiesApp.bounties.home.title">Bounties</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-bounties" [routerLink]="['/bounties/new']">
            <fa-icon icon="plus"></fa-icon>
            <span class="hidden-sm-down"  jhiTranslate="bountiesApp.bounties.home.createLabel">
            Create a new Bounties
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="row">
        <div class="col-sm-12">
            <form name="searchForm" class="form-inline">
                <div class="input-group w-100 mt-3">
                    <input type="text" class="form-control" [(ngModel)]="currentSearch" id="currentSearch" name="currentSearch" placeholder="{{ 'bountiesApp.bounties.home.search' | translate }}">

                    <button class="input-group-append btn btn-info" (click)="search(currentSearch)">
                        <fa-icon icon="search"></fa-icon>
                    </button>

                    <button class="input-group-append btn btn-danger" (click)="search('')" *ngIf="currentSearch">
                        <fa-icon icon="trash-alt"></fa-icon>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="alert alert-warning" id="no-result" *ngIf="bounties?.length === 0">
        <span jhiTranslate="bountiesApp.bounties.home.notFound">No bounties found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="bounties && bounties.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span jhiTranslate="global.field.id">ID</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounties.status">Status</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounties.url">Url</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounties.amount">Amount</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounties.type">Type</span></th>
                    <th scope="col" ><span jhiTranslate="bountiesApp.bounties.category">Category</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let bounties of bounties ;trackBy: trackId">
                    <td><a [routerLink]="['/bounties', bounties.id, 'view']">{{ bounties.id }}</a></td>
                    <td>{{ bounties.status }}</td>
                    <td>{{ bounties.url }}</td>
                    <td>{{ bounties.amount }}</td>
                    <td>{{ bounties.type }}</td>
                    <td>{{ bounties.category }}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/bounties', bounties.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/bounties', bounties.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(bounties)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
