// src/main/webapp/app/entities/bounties/bounties-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IIssue } from 'app/shared/model/issue.model';
import { getEntities as getIssues } from 'app/entities/issue/issue.reducer';
import { getEntity, updateEntity, createEntity, reset } from './bounties.reducer';
import { IBounties } from 'app/shared/model/bounties.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IBountiesUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const BountiesUpdate = (props: IBountiesUpdateProps) => {
  const [issueId, setIssueId] = useState('0');
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { bountiesEntity, issues, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/bounties');
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getIssues();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...bountiesEntity,
        ...values,
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="bountiesApp.bounties.home.createOrEditLabel">Create or edit a Bounties</h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : bountiesEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="bounties-id">ID</Label>
                  <AvInput id="bounties-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="statusLabel" for="bounties-status">
                  Status
                </Label>
                <AvInput
                  id="bounties-status"
                  type="select"
                  className="form-control"
                  name="status"
                  value={(!isNew && bountiesEntity.status) || 'OPEN'}
                >
                  <option value="OPEN">OPEN</option>
                  <option value="INVALID">INVALID</option>
                  <option value="CLOSED">CLOSED</option>
                  <option value="FUNDED">FUNDED</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="urlLabel" for="bounties-url">
                  Url
                </Label>
                <AvField id="bounties-url" type="text" name="url" />
              </AvGroup>
              <AvGroup>
                <Label id="amountLabel" for="bounties-amount">
                  Amount
                </Label>
                <AvField id="bounties-amount" type="text" name="amount" />
              </AvGroup>
              <AvGroup>
                <Label id="experienceLabel" for="bounties-experience">
                  Experience
                </Label>
                <AvInput
                  id="bounties-experience"
                  type="select"
                  className="form-control"
                  name="experience"
                  value={(!isNew && bountiesEntity.experience) || 'BEGINNER'}
                >
                  <option value="BEGINNER">BEGINNER</option>
                  <option value="INTERMEDIATE">INTERMEDIATE</option>
                  <option value="ADVANCED">ADVANCED</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="commitmentLabel" for="bounties-commitment">
                  Commitment
                </Label>
                <AvField id="bounties-commitment" type="string" className="form-control" name="commitment" />
              </AvGroup>
              <AvGroup>
                <Label id="typeLabel" for="bounties-type">
                  Type
                </Label>
                <AvInput
                  id="bounties-type"
                  type="select"
                  className="form-control"
                  name="type"
                  value={(!isNew && bountiesEntity.type) || 'BUG'}
                >
                  <option value="BUG">BUG</option>
                  <option value="FEATURE">FEATURE</option>
                  <option value="IMPROVEMENT">IMPROVEMENT</option>
                  <option value="EX">EX</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="categoryLabel" for="bounties-category">
                  Category
                </Label>
                <AvInput
                  id="bounties-category"
                  type="select"
                  className="form-control"
                  name="category"
                  value={(!isNew && bountiesEntity.category) || 'FRONT_END'}
                >
                  <option value="FRONT_END">FRONT_END</option>
                  <option value="BACKEND">BACKEND</option>
                  <option value="THIS">THIS</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="keywordsLabel" for="bounties-keywords">
                  Keywords
                </Label>
                <AvField id="bounties-keywords" type="text" name="keywords" />
              </AvGroup>
              <AvGroup check>
                <Label id="permissionLabel">
                  <AvInput id="bounties-permission" type="checkbox" className="form-check-input" name="permission" />
                  Permission
                </Label>
              </AvGroup>
              <AvGroup>
                <Label id="expiresLabel" for="bounties-expires">
                  Expires
                </Label>
                <AvField id="bounties-expires" type="date" className="form-control" name="expires" />
              </AvGroup>
              <AvGroup>
                <Label for="bounties-issue">Issue</Label>
                <AvInput id="bounties-issue" type="select" className="form-control" name="issue.id">
                  <option value="" key="0" />
                  {issues
                    ? issues.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/bounties" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">Back</span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp; Save
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  issues: storeState.issue.entities,
  bountiesEntity: storeState.bounties.entity,
  loading: storeState.bounties.loading,
  updating: storeState.bounties.updating,
  updateSuccess: storeState.bounties.updateSuccess,
});

const mapDispatchToProps = {
  getIssues,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(BountiesUpdate);

// src/main/webapp/app/entities/bounties/bounties-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { IBounties, Bounties } from 'app/shared/model/bounties.model';
import { BountiesService } from './bounties.service';

@Component({
  selector: 'jhi-bounties-update',
  templateUrl: './bounties-update.component.html',
})
export class BountiesUpdateComponent implements OnInit {
  isSaving = false;
  expiresDp: any;

  editForm = this.fb.group({
    id: [],
    status: [],
    url: [],
    amount: [],
    experience: [],
    commitment: [],
    type: [],
    category: [],
    keywords: [],
    permission: [],
    expires: [],
  });

  constructor(protected bountiesService: BountiesService, protected activatedRoute: ActivatedRoute, private fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ bounties }) => {
      this.updateForm(bounties);
    });
  }

  updateForm(bounties: IBounties): void {
    this.editForm.patchValue({
      id: bounties.id,
      status: bounties.status,
      url: bounties.url,
      amount: bounties.amount,
      experience: bounties.experience,
      commitment: bounties.commitment,
      type: bounties.type,
      category: bounties.category,
      keywords: bounties.keywords,
      permission: bounties.permission,
      expires: bounties.expires,
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const bounties = this.createFromForm();
    if (bounties.id !== undefined) {
      this.subscribeToSaveResponse(this.bountiesService.update(bounties));
    } else {
      this.subscribeToSaveResponse(this.bountiesService.create(bounties));
    }
  }

  private createFromForm(): IBounties {
    return {
      ...new Bounties(),
      id: this.editForm.get(['id'])!.value,
      status: this.editForm.get(['status'])!.value,
      url: this.editForm.get(['url'])!.value,
      amount: this.editForm.get(['amount'])!.value,
      experience: this.editForm.get(['experience'])!.value,
      commitment: this.editForm.get(['commitment'])!.value,
      type: this.editForm.get(['type'])!.value,
      category: this.editForm.get(['category'])!.value,
      keywords: this.editForm.get(['keywords'])!.value,
      permission: this.editForm.get(['permission'])!.value,
      expires: this.editForm.get(['expires'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IBounties>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-bounties-heading" jhiTranslate="bountiesApp.bounties.home.createOrEditLabel">Create or edit a Bounties</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="bountiesApp.bounties.status" for="field_status">Status</label>
                    <select class="form-control" name="status" formControlName="status" id="field_status">
                        <option value="OPEN">{{ 'bountiesApp.Status.OPEN' | translate }}</option>
                        <option value="INVALID">{{ 'bountiesApp.Status.INVALID' | translate }}</option>
                        <option value="CLOSED">{{ 'bountiesApp.Status.CLOSED' | translate }}</option>
                        <option value="FUNDED">{{ 'bountiesApp.Status.FUNDED' | translate }}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="bountiesApp.bounties.url" for="field_url">Url</label>
                    <input type="text" class="form-control" name="url" id="field_url"
                           formControlName="url"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="bountiesApp.bounties.amount" for="field_amount">Amount</label>
                    <input type="number" class="form-control" name="amount" id="field_amount"
                           formControlName="amount"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="bountiesApp.bounties.experience" for="field_experience">Experience</label>
                    <select class="form-control" name="experience" formControlName="experience" id="field_experience">
                        <option value="BEGINNER">{{ 'bountiesApp.Experience.BEGINNER' | translate }}</option>
                        <option value="INTERMEDIATE">{{ 'bountiesApp.Experience.INTERMEDIATE' | translate }}</option>
                        <option value="ADVANCED">{{ 'bountiesApp.Experience.ADVANCED' | translate }}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="bountiesApp.bounties.commitment" for="field_commitment">Commitment</label>
                    <input type="number" class="form-control" name="commitment" id="field_commitment"
                           formControlName="commitment"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="bountiesApp.bounties.type" for="field_type">Type</label>
                    <select class="form-control" name="type" formControlName="type" id="field_type">
                        <option value="BUG">{{ 'bountiesApp.Type.BUG' | translate }}</option>
                        <option value="FEATURE">{{ 'bountiesApp.Type.FEATURE' | translate }}</option>
                        <option value="IMPROVEMENT">{{ 'bountiesApp.Type.IMPROVEMENT' | translate }}</option>
                        <option value="EX">{{ 'bountiesApp.Type.EX' | translate }}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="bountiesApp.bounties.category" for="field_category">Category</label>
                    <select class="form-control" name="category" formControlName="category" id="field_category">
                        <option value="FRONT_END">{{ 'bountiesApp.Category.FRONT_END' | translate }}</option>
                        <option value="BACKEND">{{ 'bountiesApp.Category.BACKEND' | translate }}</option>
                        <option value="THIS">{{ 'bountiesApp.Category.THIS' | translate }}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="bountiesApp.bounties.keywords" for="field_keywords">Keywords</label>
                    <input type="text" class="form-control" name="keywords" id="field_keywords"
                           formControlName="keywords"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="bountiesApp.bounties.permission" for="field_permission">Permission</label>
                    <input type="checkbox" class="form-control" name="permission" id="field_permission"
                           formControlName="permission"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="bountiesApp.bounties.expires" for="field_expires">Expires</label>
                    <div class="input-group">
                        <input id="field_expires" type="text" class="form-control" name="expires" ngbDatepicker #expiresDp="ngbDatepicker" formControlName="expires"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="expiresDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
                        </span>
                    </div>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
